/**
 * Every icon the portal uses, and the only file that imports the icon libraries. Both ship as SVG
 * components, so only the icons used travel to the browser.
 * - Phosphor: the set of the final design (design/DESIGN.md). Screens move to it one at a time,
 *   as each is rebuilt; the login is the first. Its names carry the `Ph` prefix.
 * - Bootstrap Icons 1.11, the set of the original Booking Web: every screen not rebuilt yet.
 *
 * Icons are decorative: give them aria-hidden, and let the text next to them, or the button's
 * aria-label, be what a screen reader announces. The kit's components already do.
 */
export {
  ArrowCounterclockwise as IconReactivated,
  ArrowRepeat as IconRoundTrip,
  BellFill as IconBell,
  BoxArrowInRight as IconLogin,
  BoxArrowRight as IconLogout,
  Buildings as IconCatalog,
  Building as IconBuilding,
  Calendar3 as IconCalendar,
  CalendarCheck as IconScheduled,
  CalendarWeek as IconTrips,
  CarFrontFill as IconOnTheWay,
  CashCoin as IconBilling,
  CheckCircleFill as IconCheckCircle,
  Check2 as IconCheck,
  Check2All as IconCheckAll,
  ChevronDown as IconChevronDown,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  Clipboard as IconCopy,
  Clock as IconClock,
  Envelope as IconEmail,
  ExclamationTriangleFill as IconWarning,
  Eye as IconShow,
  EyeSlash as IconHide,
  FileEarmarkSpreadsheet as IconExport,
  FlagFill as IconCompleted,
  Funnel as IconFilter,
  GeoAltFill as IconPin,
  Globe2 as IconWebsite,
  Hospital as IconHospital,
  Inbox as IconInbox,
  InfoCircle as IconInfo,
  KeyFill as IconKey,
  ListUl as IconList,
  Map as IconMap,
  Paperclip as IconAttachment,
  PencilSquare as IconEdit,
  PeopleFill as IconUsers,
  PersonCircle as IconUser,
  PersonFill as IconPatient,
  PinMapFill as IconTrack,
  PlusLg as IconPlus,
  Search as IconSearch,
  ShieldLockFill as IconAdmin,
  SlashCircle as IconDisable,
  Telephone as IconPhone,
  Translate as IconLanguage,
  Trash3 as IconDelete,
  TruckFrontFill as IconProvider,
  XCircleFill as IconCancelled,
  XLg as IconClose,
} from "react-bootstrap-icons";

export {
  ArrowClockwise as PhArrowClockwise,
  ArrowLeft as PhArrowLeft,
  Bell as PhBell,
  BellRinging as PhBellRinging,
  Buildings as PhBuildings,
  CalendarBlank as PhCalendarBlank,
  CalendarPlus as PhCalendarPlus,
  CalendarX as PhCalendarX,
  CaretDown as PhCaretDown,
  CaretUpDown as PhCaretUpDown,
  ChartLineUp as PhChartLineUp,
  Check as PhCheck,
  CheckCircle as PhCheckCircle,
  CircleNotch as PhCircleNotch,
  ClockCountdown as PhClockCountdown,
  Crosshair as PhCrosshair,
  DotsThree as PhDotsThree,
  DownloadSimple as PhDownloadSimple,
  Eye as PhEye,
  EyeSlash as PhEyeSlash,
  FileCsv as PhFileCsv,
  GlobeHemisphereWest as PhGlobe,
  Info as PhInfo,
  Key as PhKey,
  MagnifyingGlass as PhMagnifyingGlass,
  MoonStars as PhMoonStars,
  NavigationArrow as PhNavigationArrow,
  Path as PhPath,
  Phone as PhPhone,
  PencilSimple as PhPencilSimple,
  Plus as PhPlus,
  Minus as PhMinus,
  Rows as PhRows,
  ShieldCheck as PhShieldCheck,
  SignIn as PhSignIn,
  SidebarSimple as PhSidebarSimple,
  SignOut as PhSignOut,
  Sun as PhSun,
  TextAa as PhTextAa,
  UserCircle as PhUserCircle,
  Van as PhVan,
  Warning as PhWarning,
  WarningCircle as PhWarningCircle,
  WifiSlash as PhWifiSlash,
  X as PhX,
  XCircle as PhXCircle,
} from "@phosphor-icons/react";
