/**
 * Every icon the portal uses, and the only file that imports the icon library (Bootstrap Icons
 * 1.11, the set of the original Booking Web, as SVG components: only these travel to the browser).
 * When the final design brings another set, this is the one file that changes.
 *
 * Icons are decorative: give them aria-hidden, and let the text next to them, or the button's
 * aria-label, be what a screen reader announces. The kit's components already do.
 */
export {
  ArrowCounterclockwise as IconReactivated,
  ArrowRepeat as IconRoundTrip,
  BellFill as IconBell,
  BoxArrowInRight as IconLogin,
  BoxArrowRight as IconLogout,
  Buildings as IconCatalog,
  Building as IconBuilding,
  Calendar3 as IconCalendar,
  CalendarCheck as IconScheduled,
  CalendarWeek as IconTrips,
  CarFrontFill as IconOnTheWay,
  CashCoin as IconBilling,
  CheckCircleFill as IconCheckCircle,
  Check2 as IconCheck,
  Check2All as IconCheckAll,
  ChevronDown as IconChevronDown,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  Clipboard as IconCopy,
  Clock as IconClock,
  Envelope as IconEmail,
  ExclamationTriangleFill as IconWarning,
  Eye as IconShow,
  EyeSlash as IconHide,
  FileEarmarkSpreadsheet as IconExport,
  FlagFill as IconCompleted,
  Funnel as IconFilter,
  GeoAltFill as IconPin,
  Globe2 as IconWebsite,
  Hospital as IconHospital,
  Inbox as IconInbox,
  InfoCircle as IconInfo,
  KeyFill as IconKey,
  ListUl as IconList,
  Map as IconMap,
  Paperclip as IconAttachment,
  PencilSquare as IconEdit,
  PeopleFill as IconUsers,
  PersonCircle as IconUser,
  PersonFill as IconPatient,
  PinMapFill as IconTrack,
  PlusLg as IconPlus,
  Search as IconSearch,
  ShieldLockFill as IconAdmin,
  SlashCircle as IconDisable,
  Telephone as IconPhone,
  Translate as IconLanguage,
  Trash3 as IconDelete,
  TruckFrontFill as IconProvider,
  XCircleFill as IconCancelled,
  XLg as IconClose,
} from "react-bootstrap-icons";
